### ISSUE TITLE
emelFM2 crashes when suspended in terminal

### ISSUE THREAD

**Issue by landroni** [tom2tom/emelfm2#3]
To reproduce with 0.9.1: 
- execute `emelfm2` in terminal
- `ctrl+z` in terminal to stop process
- `bg` in terminal
- switch back to emelFM2 window

At this point you should get a crash.  

```
(gdb) run
Starting program: /usr/bin/emelfm2 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdb619700 (LWP 8056)]

(emelfm2:8051): Gtk-CRITICAL **: IA__gtk_icon_set_render_icon: assertion 'icon_set != NULL' failed

(emelfm2:8051): Gtk-CRITICAL **: IA__gtk_icon_set_render_icon: assertion 'icon_set != NULL' failed
[New Thread 0x7fffdab58700 (LWP 8057)]
[New Thread 0x7fffda357700 (LWP 8058)]
[Thread 0x7fffdab58700 (LWP 8057) exited]
[Thread 0x7fffda357700 (LWP 8058) exited]
^Z
Program received signal SIGTSTP, Stopped (user).
0x00007ffff5285fbd in poll () at ../sysdeps/unix/syscall-template.S:81
81  ../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt
#0  0x00007ffff5285fbd in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff62e2fe4 in g_main_context_poll (priority=2147483647, n_fds=2, fds=0x10187e0, timeout=254, context=0x6fa0e0) at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:4028
#2  g_main_context_iterate (context=0x6fa0e0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3729
#3  0x00007ffff62e330a in g_main_loop_run (loop=0x7179f0) at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3928
#4  0x00007ffff78c9447 in IA__gtk_main () at /build/buildd/gtk+2.0-2.24.23/gtk/gtkmain.c:1271
#5  0x0000000000422cd7 in main ()
(gdb) q
```

**Comment by tom2tom** [comment]
On Tue, 25 Aug 2015 02:14:14 -0700
landroni notifications@github.com wrote:

Should be fixed now - removed SIGTSTP from signals which end the session.

Regards
Tom

**Comment by landroni** [comment]
The issue is not fixed in latest GIT. Follow same steps as described above, and then do any operation within emelFM2 (e.g. enter a folder).

**Comment by landroni** [comment]
Sorry, false alarm. The issue is fixed.
