### ISSUE TITLE
crash when renaming & replacing file

### ISSUE THREAD

**Issue by landroni** [tom2tom/emelfm2#4]
I've got a crash where emelFM2 (latest release) gets confused after a rename & replace operation. I had `pnmixer_0.6.orig.tar.gz` and `pnmixer_0.6.tar.gz`. Renamed the latter to `pnmixer_0.6.orig.tar.gz`, replaced other file. Then emelFM2 displays both files in the file list, I go back out of the folder, get back in, and around that time emelFM2 will trigger a crash. 

I got a trace, but not sure it says much: 

```
(gdb) run
Starting program: /usr/bin/emelfm2 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdb587700 (LWP 8067)]

(emelfm2:8063): Gtk-CRITICAL **: IA__gtk_icon_set_render_icon: assertion 'icon_set != NULL' failed

(emelfm2:8063): Gtk-CRITICAL **: IA__gtk_icon_set_render_icon: assertion 'icon_set != NULL' failed
[New Thread 0x7fffdaac6700 (LWP 8068)]
[New Thread 0x7fffda2c5700 (LWP 8069)]
[Thread 0x7fffdaac6700 (LWP 8068) exited]
[Thread 0x7fffda2c5700 (LWP 8069) exited]
[New Thread 0x7fffda2c5700 (LWP 8070)]
[Thread 0x7fffda2c5700 (LWP 8070) exited]
[New Thread 0x7fffda2c5700 (LWP 8071)]
[Thread 0x7fffda2c5700 (LWP 8071) exited]
[New Thread 0x7fffda2c5700 (LWP 8073)]
[Thread 0x7fffda2c5700 (LWP 8073) exited]
[New Thread 0x7fffda2c5700 (LWP 8074)]
[Thread 0x7fffda2c5700 (LWP 8074) exited]
[New Thread 0x7fffda2c5700 (LWP 8075)]
[Thread 0x7fffda2c5700 (LWP 8075) exited]
[New Thread 0x7fffda2c5700 (LWP 8076)]
[New Thread 0x7fffdaac6700 (LWP 8078)]
[New Thread 0x7fffd9ac4700 (LWP 8079)]
[Thread 0x7fffdaac6700 (LWP 8078) exited]
[Thread 0x7fffda2c5700 (LWP 8076) exited]
[Thread 0x7fffd9ac4700 (LWP 8079) exited]
[New Thread 0x7fffd9ac4700 (LWP 8080)]
[Thread 0x7fffd9ac4700 (LWP 8080) exited]
[New Thread 0x7fffd9ac4700 (LWP 8081)]
[New Thread 0x7fffdaac6700 (LWP 8082)]
[New Thread 0x7fffda2c5700 (LWP 8083)]
[Thread 0x7fffd9ac4700 (LWP 8081) exited]
[Thread 0x7fffda2c5700 (LWP 8083) exited]
[Thread 0x7fffdaac6700 (LWP 8082) exited]
[New Thread 0x7fffdaac6700 (LWP 8084)]
[New Thread 0x7fffda2c5700 (LWP 8087)]
[New Thread 0x7fffd9ac4700 (LWP 8088)]
[Thread 0x7fffdaac6700 (LWP 8084) exited]
[Thread 0x7fffda2c5700 (LWP 8087) exited]
[Thread 0x7fffd9ac4700 (LWP 8088) exited]
[New Thread 0x7fffd9ac4700 (LWP 8089)]
[Thread 0x7fffd9ac4700 (LWP 8089) exited]
[New Thread 0x7fffd9ac4700 (LWP 8090)]
[Thread 0x7fffd9ac4700 (LWP 8090) exited]
[New Thread 0x7fffd9ac4700 (LWP 8091)]
[Thread 0x7fffd9ac4700 (LWP 8091) exited]
[New Thread 0x7fffd9ac4700 (LWP 8092)]
[Thread 0x7fffd9ac4700 (LWP 8092) exited]
[New Thread 0x7fffd9ac4700 (LWP 8093)]
[New Thread 0x7fffda2c5700 (LWP 8095)]
[New Thread 0x7fffdaac6700 (LWP 8096)]
[Thread 0x7fffd9ac4700 (LWP 8093) exited]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffda2c5700 (LWP 8095)]
magazine_chain_pop_head (magazine_chunks=0x7fffc401c8b0) at /build/buildd/glib2.0-2.40.2/./glib/gslice.c:539
539 /build/buildd/glib2.0-2.40.2/./glib/gslice.c: No such file or directory.
(gdb) bt
#0  magazine_chain_pop_head (magazine_chunks=0x7fffc401c8b0) at /build/buildd/glib2.0-2.40.2/./glib/gslice.c:539
#1  thread_memory_magazine1_alloc (tmem=<optimized out>, ix=24) at /build/buildd/glib2.0-2.40.2/./glib/gslice.c:842
#2  g_slice_alloc (mem_size=400) at /build/buildd/glib2.0-2.40.2/./glib/gslice.c:998
#3  0x0000000000427947 in e2_filelist_make_all_infos ()
#4  0x0000000000428888 in ?? ()
#5  0x0000000000429467 in ?? ()
#6  0x00007ffff5566182 in start_thread (arg=0x7fffda2c5700) at pthread_create.c:312
#7  0x00007ffff529330d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) q
```

**Comment by tom2tom** [comment]
On Wed, 02 Sep 2015 14:27:55 -0700
landroni notifications@github.com wrote:

> I've got a crash where emelFM2 (latest release) gets confused after a rename & replace operation. I had `pnmixer_0.6.orig.tar.gz` and `pnmixer_0.6.tar.gz`. Renamed the latter to `pnmixer_0.6.orig.tar.gz`, replaced other file. Then emelFM2 displays both files in the file list, I go back out of the folder, get back in, and around that time emelFM2 will trigger a crash. 

Not sure what you mean by "latest release". Some changes were committed to github (and svn) a few weeks ago, intended to deal with that sort of crash. Can you confirm that they're not sufficient?

Tom

**Comment by landroni** [comment]
I used 0.9.1 for this crash. Will try GIT to see if it helps...

**Comment by landroni** [comment]
Can't reproduce the crash with GIT. Closing...
